### ISSUE TITLE
balajs can not minify by uglifyJs

### ISSUE THREAD

**Issue by rockliuxn** [finom/bala#5]
Hi, I'm getting the following error when I  npm run build 

`ERROR in static/js/1.d5d07df3cdfb67f13252.js from UglifyJs`
`SyntaxError: Unexpected token: operator (>) [./~/balajs/bala.umd.js:2,0]`

I searched for a bit,   it's related to uglify not being able to minify es6, balajs use es6, so the build fails,  @finom  can you help solve this problem, thank you very much !

**Comment by finom** [comment]
@rockliuxn bala.js v1 isn't compatible with ES5 anymore. There are few ideas how you can solve your issue:

- Use [bala.js v0](https://github.com/finom/bala/tree/6d0122febd9ba2cc0a1d57e839dfa39390500d42): `npm install balajs@0`.
- Use [Babel](https://babeljs.io/docs/usage/cli/) to compile the function to ES5 (you also can do it [manually](https://babeljs.io/repl)).
- Use UglifyJS 2 from [harmony branch](https://github.com/mishoo/UglifyJS2/tree/harmony).

At your package.json it should look like:
```js
"devDependencies": {
  "uglify-js": "github:mishoo/UglifyJS2#harmony"
}
```
Or use [unofficial package](https://www.npmjs.com/package/uglify-js-harmony).

Hope this helps.

**Comment by finom** [comment]
@fronteed is solved an issue when Gulp and Babelify (which didn't transpile code from node_modules) are used:
```js
.transform('babelify', {
  global: true,
  ignore: /\/node_modules\/(?!balajs\/)/
})
```

**Comment by finom** [comment]
Finally decided to move back es5 version and import it by default from node_modules. Unfortunately UglifyJS team isn't interested to publish their harmony version and bala.js takes time to understand why code isn't minified.

I'm going to get rid of es5 version as soon as the new version of UglifyJS is published.
